..  |AFIT|                  replace:: *Air Force Institute of Technology*
..  _AFIT:                  https://www.afit.edu/

..  |ANTLR|                 replace:: *ANother Tool for Language Recognition*
..  _ANTLR:                 https://www.antlr.org/
..  _AppVeyor:              https://www.appveyor.com/

..  |AST|                   replace:: *Abstract Syntax Tree*
..  |CFD|                   replace::   *Computational Fluid Dynamics*
..  _CFD:                   https://en.wikipedia.org/wiki/Computational_fluid_dynamics

..  |CI|                    replace::   *Continuous Integration*

..  _Click:                  https://palletsprojects.com/p/click/
..  _Coveralls:             https://coveralls.io/
..  |EBNF|                  replace:: *Extended Bakus-Naur Form*
..  _EBNF:                  https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form
..  _FedEx:                 https://www.fedex.com/en-us/home.html

..  |Gadfly|                replace:: Hendersen-Glenny Gadfly
..  _Gadfly:                https://en.wikipedia.org/wiki/Henderson-Glenny_Gadfly

..	|GH|	                replace:: *GitHub*
..	_GH:	                https://github.com/

..	_Git:	                https://git-scm.com/

..  _given when then:       https://martinfowler.com/bliki/GivenWhenThen.html

..  _Homebrew:              https://brew.sh/
..  _Linus Torvalds:        https://en.wikipedia.org/wiki/Linus_Torvalds

..  |LPP|                   replace:: *Limited Pennyplane*

..  _Make:                  https://www.gnu.org/software/make/

..  |MMAKE|                 replace::   *Modular Make*
..  _MMAKE:                 https://github.com/rblack42/modular-make/

..  |MM|                    replace::   *Math-Magik*
..  _MM:                    https://github.com/rblack42/math-magik

..  _numpy-stl:             https://pypi.org/project/numpy-stl/

..  _OpenSCAD:              https://openscad.org/

..  |OS|                    replace::   *Open Source*
..  |OSC|                   replace::   *OpenSCAD*

..	|PY|	                replace::	*Python*
..	_PY:	                https://www.python.org/

..  |PyPi|                  replace:: *Python Package Index*
..  _PyPi:                  https://pypi.org/

..  _PyCharm:               https://www.jetbrains.com/pycharm/
..  _PyTest:                https://docs.pytest.org/en/6.2.x/
..  |RST|                   replace:: *reStructuredText*

..  _semantic versioning:   https://semver.org/

..  _Sphinx:                https://www.sphinx-doc.org/en/master/

..  _TatSu:                https://tatsu.readthedocs.io/en/stable/index.html

..  |TDD|                   replace::   *Test Driven Development*

..  _tkinter:               https://docs.python.org/3/library/tkinter.html

..  _Travis-CI:             https://travis-ci.com/

..  _Ubuntu:                https://ubuntu.com/
